force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Rent_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rent_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/UPI_ID__c.field-meta.xml
<CustomField>
    <fullName>UPI_ID__c</fullName>
    <label>UPI-ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/Transaction_BigData__b.object-meta.xml
<CustomObject>
    <label>Transaction_BigData</label>
    <pluralLabel>Transactions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Transaction_BigData__b/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/UPI_ID__c.field-meta.xml
<CustomField>
    <fullName>UPI_ID__c</fullName>
    <label>UPI-ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/createRecord_New.cls
public class createRecord_New {
    //@future
    /*
     * public static void testMethod1(Transaction__c Txn){
        
        List<Transaction_BigData__b> BtxnL = new List<Transaction_BigData__b>();
        
        //for (Transaction__c txn : TxnList) {        
        Transaction_BigData__b Btxn = new Transaction_BigData__b();
        Btxn.Name__C = txn.Name;
        Btxn.Transaction_Date__c = txn.Paid_Date__c;
        Btxn.Amount__C = txn.Rent_Amount__c;
        Btxn.UPI_ID__c = txn.UPI_ID__c;
        BtxnL.add(Btxn);
        //}
        if (!BtxnL.isEmpty()) {
            Database.insertImmediate(BtxnL);
        }
    
    }
*/

}