force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Paid by</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Rents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/UPI_ID__c.field-meta.xml
<CustomField>
    <fullName>UPI_ID__c</fullName>
    <label>UPI-ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/Transaction_BigData__b.object-meta.xml
<CustomObject>
    <label>Transaction_BigData</label>
    <pluralLabel>Transactions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Transaction_BigData__b/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/Created_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Created_DateTime__c</fullName>
    <label>Created DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/UPI_ID__c.field-meta.xml
<CustomField>
    <fullName>UPI_ID__c</fullName>
    <label>UPI-ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/createRecordOnTxnBigObject.cls
public class createRecordOnTxnBigObject {    
    @future
    public static void receiveParameters(String IdT,String IdC, String Name, Date Paid_Date,Decimal Rent_Amount, String UPIid) {
        //Process the received parameters
        //System.debug('Received message: ' + message);
        //System.debug('Received number: ' + number);
        
        Transaction_BigData__b Btxn = new Transaction_BigData__b();
        Btxn.Transaction__C = IdT;
        Btxn.Name__C = Name;
        Btxn.Transaction_Date__c = Paid_Date;
        Btxn.created_DateTime__C  = DateTime.now();
        Btxn.Amount__C = Rent_Amount;
        Btxn.UPI_ID__c = UPIid;  
        //if(IdC!=null)
        Btxn.Contact__C = ''+IdC;
        database.insertImmediate(Btxn);

    }
}