force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Paid by</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Rents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>UPI Credit Card</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/RefNo__c.field-meta.xml
<CustomField>
    <fullName>RefNo__c</fullName>
    <label>RefNo</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Rent_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rent_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>Balance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/UPI_ID__c.field-meta.xml
<CustomField>
    <fullName>UPI_ID__c</fullName>
    <label>UPI-ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/dailyCleanUp.cls
global class dailyCleanUp implements Schedulable{
    global void execute(SchedulableContext sc) {
        // Your logic here
        System.debug('class : dailyCleanUp -> method : execute -> loc : start');
        System.debug('Scheduled Apex is running!');
        transactionDescriptionCleanup();
        System.debug('class : dailyCleanUp -> method : execute -> loc : end');
        
    }


    public static void transactionDescriptionCleanup()
    {
		system.debug('class : dailyCleanUp -> method : transactionDescriptionCleanup -> loc : start');

	 	String queryTransaction ='SELECT Id, Name, LastModifiedDate, Payment_Mode__c, Rent_Amount__c, Contact__c, Paid_Date__c, UPI_ID__c, Type__c, BankAccount__c, Description__c, RefNo__c FROM transaction__c WHERE LastModifiedDate = THIS_WEEK AND LastModifiedDate != TODAY AND LastModifiedDate != YESTERDAY';
        List<Transaction__C> resultTransaction =  Database.query(queryTransaction);
        for(Transaction__C txn: resultTransaction){
            if (txn.Payment_Mode__c!=null &&	txn.Rent_Amount__c!=null &&	txn.Contact__c!=null &&	txn.Paid_Date__c!=null && txn.UPI_ID__c!=null && txn.Type__c!=null && txn.BankAccount__c!=null)
                if( txn.Description__c.contains('#'))
                	txn.Description__c='';
        }
		system.debug('class : dailyCleanUp -> method : transactionDescriptionCleanup -> loc : before update | Update content = resultTransaction = '+resultTransaction);

        update resultTransaction;
		system.debug('class : dailyCleanUp -> method : transactionDescriptionCleanup -> loc : End');


    }
    public static void dailyCleanUp(){
        //Purpose is to remove the description of a record when its last modifiled is more than 24 hrs at the time of this exicution.
    	system.debug('class : dailyCleanUp -> method : dailyCleanUp -> loc : start');
    }

}