force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Paid by</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Rents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/UPI_ID__c.field-meta.xml
<CustomField>
    <fullName>UPI_ID__c</fullName>
    <label>UPI-ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/Transaction_BigData__b.object-meta.xml
<CustomObject>
    <label>Transaction_BigData</label>
    <pluralLabel>Transactions</pluralLabel>
</CustomObject>

force-app/main/default/objects/Transaction_BigData__b/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/Created_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Created_DateTime__c</fullName>
    <label>Created DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction_BigData__b/fields/UPI_ID__c.field-meta.xml
<CustomField>
    <fullName>UPI_ID__c</fullName>
    <label>UPI-ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BigObjectController.cls
public class BigObjectController {
    @AuraEnabled(cacheable=true)
    public static List<Transaction_BigData__b> getTransactionBigDataRecords(){
        System.debug(' BigObjectController > getTransactionBigDataRecords > Start');
        List<Transaction_BigData__b> txnBigList = new List<Transaction_BigData__b>();
        txnBigList = [SELECT Id, CreatedById, CreatedDate, SystemModstamp, Created_DateTime__c, Contact__c, UPI_ID__c, Amount__c, Name__c, Transaction_Date__c, Transaction__c  FROM Transaction_BigData__b LIMIT 50];
    	return txnBigList;
    }
    @AuraEnabled(cacheable=true)
    public static List<Transaction_BigData__b> getTransactionBigDataRecordsforContact(String contactId){
        System.debug(' BigObjectController > getTransactionBigDataRecordsforContact > Start');
        List<Transaction_BigData__b> txnBigList = new List<Transaction_BigData__b>();
        txnBigList = [SELECT Id, CreatedById, CreatedDate, SystemModstamp, Created_DateTime__c, Contact__c, UPI_ID__c, Amount__c, Name__c, Transaction_Date__c, Transaction__c  FROM Transaction_BigData__b  LIMIT 10000];
    	List<Transaction_BigData__b> txnBigListRec = new List<Transaction_BigData__b>();
        for(Transaction_BigData__b txn : txnBigList){
            if(txn.Contact__C == contactId)
            	txnBigListRec.add(txn);
        }
        return txnBigListRec;
    }
}